### ISSUE TITLE
请问如何与其他语言结合呢？

### ISSUE THREAD

**Issue by ygcool** [oldfritter/matching#2]
请问如何使用这个项目呢？其他开发语言负责前台api接口，用户下单后推送到这个撮合引擎，撮合完成通知api服务。

**Comment by oldfritter** [comment]
@ygcool 
你可以参考[goDCE](https://github.com/oldfritter/goDCE/blob/master/trade/matching.go)

**Comment by oldfritter** [comment]
一般做法是使用golang写一个独立撮合引擎，与项目的其它节点通过消息总线或者其它方式通信

**Comment by ygcool** [comment]
好的，谢谢
